<!--
This file is part of Wisp Framework.

Licensed under either of
  * Apache License, Version 2.0 (https://www.apache.org/licenses/LICENSE-2.0)
  * MIT License (https://opensource.org/licenses/MIT)
at your option.
-->

<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="coverlet.collector" Version="6.0.4" />
    <PackageReference Include="coverlet.msbuild" Version="6.0.4">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="18.0.1" />
    <PackageReference Include="xunit" Version="2.9.3" />
    <PackageReference Include="xunit.runner.visualstudio" Version="3.1.5" />

    <ProjectReference Include="../Wisp.Framework/Wisp.Framework.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Include="appsettings.Test.json" CopyToOutputDirectory="Always" CopyToPublishDirectory="Always" />
    
    <Using Include="Xunit" />
    
    <None Update="Templates\_layout.liquid">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
