<!--
This file is part of Wisp Framework.

Licensed under either of
  * Apache License, Version 2.0 (https://www.apache.org/licenses/LICENSE-2.0)
  * MIT License (https://opensource.org/licenses/MIT)
at your option.
-->

<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <PackageReadmeFile>README.md</PackageReadmeFile>
        <PackageLicenseExpression>MIT OR Apache-2.0</PackageLicenseExpression>

        <Version>10.0.0</Version>
        
        <PackageId>Wisp.Extensions.OpenApi</PackageId>
        <Authors>Jakub Sycha (utf-8x)</Authors>
        <Company>Wisp</Company>
        <Description>An OpenAPI schema generator and Swagger UI for the Wisp Framework</Description>
        <PackageProjectUrl>https://codeberg.org/WispFramework/Wisp</PackageProjectUrl>
        <RepositoryUrl>https://codeberg.org/WispFramework/Wisp.git</RepositoryUrl>
        <RepositoryType>git</RepositoryType>
        <PackageTags>web,framework,lightweight,wisp</PackageTags>
        
        <PackageRequireLicenseAcceptance>false</PackageRequireLicenseAcceptance>
        <PublishRepositoryUrl>true</PublishRepositoryUrl>
        <EmbedUntrackedSources>true</EmbedUntrackedSources>
        <IncludeSymbols>true</IncludeSymbols>
        <SymbolPackageFormat>snupkg</SymbolPackageFormat>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="NSwag.Core" Version="14.6.3" />
        <PackageReference Include="Microsoft.OpenApi" Version="3.1.1" />
        <ProjectReference Include="../Wisp.Framework/Wisp.Framework.csproj" />
    </ItemGroup>
    
    <ItemGroup>
        <None Include="README.md" Pack="true" PackagePath="/" />
    </ItemGroup>
</Project>
